// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Royal.Scenes.Game.Utils.FlatLevel
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct FItemCount : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static FItemCount GetRootAsFItemCount(ByteBuffer _bb) { return GetRootAsFItemCount(_bb, new FItemCount()); }
  public static FItemCount GetRootAsFItemCount(ByteBuffer _bb, FItemCount obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FItemCount __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Type { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Count { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int BoardId { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<Royal.Scenes.Game.Utils.FlatLevel.FItemCount> CreateFItemCount(FlatBufferBuilder builder,
      int Type = 0,
      int Count = 0,
      int BoardId = 0) {
    builder.StartTable(3);
    FItemCount.AddBoardId(builder, BoardId);
    FItemCount.AddCount(builder, Count);
    FItemCount.AddType(builder, Type);
    return FItemCount.EndFItemCount(builder);
  }

  public static void StartFItemCount(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddType(FlatBufferBuilder builder, int type) { builder.AddInt(0, type, 0); }
  public static void AddCount(FlatBufferBuilder builder, int count) { builder.AddInt(1, count, 0); }
  public static void AddBoardId(FlatBufferBuilder builder, int boardId) { builder.AddInt(2, boardId, 0); }
  public static Offset<Royal.Scenes.Game.Utils.FlatLevel.FItemCount> EndFItemCount(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Royal.Scenes.Game.Utils.FlatLevel.FItemCount>(o);
  }
  public FItemCountT UnPack() {
    var _o = new FItemCountT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(FItemCountT _o) {
    _o.Type = this.Type;
    _o.Count = this.Count;
    _o.BoardId = this.BoardId;
  }
  public static Offset<Royal.Scenes.Game.Utils.FlatLevel.FItemCount> Pack(FlatBufferBuilder builder, FItemCountT _o) {
    if (_o == null) return default(Offset<Royal.Scenes.Game.Utils.FlatLevel.FItemCount>);
    return CreateFItemCount(
      builder,
      _o.Type,
      _o.Count,
      _o.BoardId);
  }
}

public class FItemCountT
{
  [Newtonsoft.Json.JsonProperty("Type")]
  public int Type { get; set; }
  [Newtonsoft.Json.JsonProperty("Count")]
  public int Count { get; set; }
  [Newtonsoft.Json.JsonProperty("BoardId")]
  public int BoardId { get; set; }

  public FItemCountT() {
    this.Type = 0;
    this.Count = 0;
    this.BoardId = 0;
  }
}


static public class FItemCountVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Type*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*Count*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*BoardId*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
