// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Royal.Scenes.Game.Utils.FlatLevel
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct FTiledSetElement : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static FTiledSetElement GetRootAsFTiledSetElement(ByteBuffer _bb) { return GetRootAsFTiledSetElement(_bb, new FTiledSetElement()); }
  public static FTiledSetElement GetRootAsFTiledSetElement(ByteBuffer _bb, FTiledSetElement obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FTiledSetElement __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int CreateRatio { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<Royal.Scenes.Game.Utils.FlatLevel.FTiledSetElement> CreateFTiledSetElement(FlatBufferBuilder builder,
      int Id = 0,
      int CreateRatio = 0) {
    builder.StartTable(2);
    FTiledSetElement.AddCreateRatio(builder, CreateRatio);
    FTiledSetElement.AddId(builder, Id);
    return FTiledSetElement.EndFTiledSetElement(builder);
  }

  public static void StartFTiledSetElement(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddId(FlatBufferBuilder builder, int id) { builder.AddInt(0, id, 0); }
  public static void AddCreateRatio(FlatBufferBuilder builder, int createRatio) { builder.AddInt(1, createRatio, 0); }
  public static Offset<Royal.Scenes.Game.Utils.FlatLevel.FTiledSetElement> EndFTiledSetElement(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Royal.Scenes.Game.Utils.FlatLevel.FTiledSetElement>(o);
  }
  public FTiledSetElementT UnPack() {
    var _o = new FTiledSetElementT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(FTiledSetElementT _o) {
    _o.Id = this.Id;
    _o.CreateRatio = this.CreateRatio;
  }
  public static Offset<Royal.Scenes.Game.Utils.FlatLevel.FTiledSetElement> Pack(FlatBufferBuilder builder, FTiledSetElementT _o) {
    if (_o == null) return default(Offset<Royal.Scenes.Game.Utils.FlatLevel.FTiledSetElement>);
    return CreateFTiledSetElement(
      builder,
      _o.Id,
      _o.CreateRatio);
  }
}

public class FTiledSetElementT
{
  [Newtonsoft.Json.JsonProperty("Id")]
  public int Id { get; set; }
  [Newtonsoft.Json.JsonProperty("CreateRatio")]
  public int CreateRatio { get; set; }

  public FTiledSetElementT() {
    this.Id = 0;
    this.CreateRatio = 0;
  }
}


static public class FTiledSetElementVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Id*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*CreateRatio*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
