// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace MyGame.Sample
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CommonRoot : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static CommonRoot GetRootAsCommonRoot(ByteBuffer _bb) { return GetRootAsCommonRoot(_bb, new CommonRoot()); }
  public static CommonRoot GetRootAsCommonRoot(ByteBuffer _bb, CommonRoot obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyCommonRoot(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, CommonRootVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CommonRoot __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartCommonRoot(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<MyGame.Sample.CommonRoot> EndCommonRoot(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<MyGame.Sample.CommonRoot>(o);
  }
  public static void FinishCommonRootBuffer(FlatBufferBuilder builder, Offset<MyGame.Sample.CommonRoot> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedCommonRootBuffer(FlatBufferBuilder builder, Offset<MyGame.Sample.CommonRoot> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class CommonRootVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
